# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  Build:
    runs-on: windows-latest
    permissions:
        contents: write
        actions: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true
          
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      # Runs a set of commands using the runners shell
      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.4.0
          haxelib git hscript-improved https://github.com/CodenameCrew/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/luckydog7/extension-webm
          haxelib run lime rebuild extension-webm windows
          haxelib install linc_luajit
          haxelib install actuate
          haxelib list

      - name: Building
        run: haxelib run lime build windows -final -D analyzer-optimize

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows Build
          path: export/release/windows/bin
          if-no-files-found: warn
